echo [32;0H
echo  __________________________________________________________________________
echo I- System Information -                                                   -I
echo I~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~I
echo I                                                                          I
echo I _____    _____                                                           I
echo I I    \  /    I  Micunymos Vista Professional                             I
echo I I  I\ \/ /I  I  Resolution: %resolution%                                            I
echo I I  I \__/ I  I  Acpi: %acpi%                                                  I
echo I ****      ****                                                           I
echo I                                                                          I
echo I Version: 1.1.1                                                           I
echo I Build: 241019a                                                           I
echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pause >nul