echo [32;0H
echo  __________________________________________________________________________
echo I- System Information -                                                   -I
echo I~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~I
echo I                                                                          I
echo I _____    _____                                                           I
echo I I    \  /    I  Micunymos Vista Basic                                    I
echo I I  I\ \/ /I  I  Resolution: %resolution%                                            I
echo I I  I \__/ I  I  Acpi: %acpi%                                                  I
echo I ****      ****                                                           I
echo I                                                                          I
echo I Version: 1.2.0                                                           I
echo I Build: 120824b                                                           I
echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pause >nul